Repository jevawin/searchthesourcecode.com, pull requests merged in 2022-04, with the labels that each got.

#13 STSC-06: ⚡️ Improve performance of profile images
  .eleventy.js
  _src/_site/_includes/_partials/preload-styles.njk
  _src/_site/_includes/_partials/styles.njk
  _src/_site/index.njk
  _src/images/.gitkeep
  _src/images/alex-clapperton.jpg
  _src/images/jamie-evawin.jpg
Labels: enhancement

#17 STSC-04: ✨ Create svg icon sprite
  _src/_site/_includes/_partials/preload-styles.njk
  _src/_site/_includes/_partials/scripts.njk
  _src/_site/_includes/_partials/styles.njk
  _src/_site/index.njk
  _src/icons/check.svg
  _src/icons/cross.svg
  _src/icons/github.svg
  _src/icons/heart.svg
  _src/icons/logo.svg
  _src/icons/search.svg
  _src/icons/spinner.svg
  _src/icons/warning.svg
  _src/scripts/updateResultsCount.ts
  _src/scripts/validateInput.ts
  package-lock.json
  package.json
  tailwind.config.js
  webpack.config.js
Labels: enhancement

#24 STSC-23: ♿️ Add aria-label to logo
  _src/_site/index.njk
Labels: bug

#25 STSC-19
  _src/scripts/updateResultsCount.ts
  _src/scripts/validateInput.ts
  package-lock.json
Labels: enhancement

#26 STSC-10: ♿️ Add skip links
  _src/_site/index.njk
  _src/styles/tailwind.css
Labels: enhancement

#30 STSC-28
  _src/_site/index.njk
  package-lock.json
  package.json
Labels: enhancement

#29 🐛 fixed Alex's URL
  _src/_site/index.njk
Labels: bug

#32 STSC-31: 💄 Update layout of results tables if single result
  _src/scripts/renderResultsTable.ts
Labels: improvement

#34 💄 standardise svg sizes, cross to stop icon
  _src/_site/index.njk
  _src/icons/check.svg
  _src/icons/cross.svg
  _src/icons/heart.svg
  _src/icons/stop.svg
  _src/icons/warning.svg
  _src/scripts/updateResultsCount.ts
  _src/scripts/validateInput.ts
Labels: improvement

#35 STSC-33: ✨ Add svgo to optimise svg icons
  _config/plugins.json
  _src/styles/tailwind.css
  package-lock.json
  package.json
  webpack.config.js
Labels: improvement
